dist: trusty
sudo: required

before_install:
language: python
python:
 - '3.6'
install:
 - pip3 install -r requirements.txt
 - pip3 install -U setuptools
 - python3 setup.py install
 - pip3 install coveralls
 - pip3 install pytest
before_script:
 - sleep 1 # this is just a placeholder
script:
 - coverage run --source=pybo ./test_script.py
 - cd tests/
 - python3 -m pytest
after_success: coveralls
